from __future__ import annotations

import html
import json
from dataclasses import asdict
from datetime import datetime
from pathlib import Path

from analyzer import AnalysisResult


def to_dict(result: AnalysisResult) -> dict:
    data = asdict(result)
    data["verdict"] = result.verdict
    data["schema_version"] = "1.0"
    data["generated_at"] = datetime.now().astimezone().isoformat(timespec="seconds")
    data["engine"] = "THZCodeSpair File Inspector"
    return data


def write_json(result: AnalysisResult, destination: str | Path) -> Path:
    path = Path(destination)
    path.write_text(json.dumps(to_dict(result), ensure_ascii=False, indent=2), encoding="utf-8")
    return path


def write_html(result: AnalysisResult, destination: str | Path) -> Path:
    path = Path(destination)
    severity_colors = {"high": "#f05263", "medium": "#e6a23c", "info": "#228be6"}
    findings = "".join(
        f'<article class="finding"><i style="background:{severity_colors.get(item.severity, "#6b7280")}"></i>'
        f'<div><h3>{html.escape(item.title)}</h3><p>{html.escape(item.detail)}</p></div>'
        f'<b>+{item.points}</b></article>' for item in result.findings
    )
    details = {
        "Path": result.path, "MIME": result.mime, "Detected type": result.file_type,
        "Size": f"{result.size:,} bytes", "Entropy": f"{result.entropy:.3f} / 8.000",
        **result.timestamps, **result.hashes, **result.metadata,
    }
    rows = "".join(f"<tr><th>{html.escape(str(k))}</th><td>{html.escape(str(v))}</td></tr>" for k, v in details.items())
    indicators = "".join(
        f"<section><h3>{html.escape(kind)} ({len(values)})</h3><pre>{html.escape(chr(10).join(values) or '—')}</pre></section>"
        for kind, values in result.indicators.items()
    )
    color = "#f05263" if result.score >= 70 else "#e6a23c" if result.score >= 40 else "#2b8a6e"
    document = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>{html.escape(result.name)} · THZCodeSpair report</title>
<style>
*{{box-sizing:border-box}}body{{margin:0;background:#f4f6f8;color:#17202a;font:14px Inter,system-ui,sans-serif}}main{{max-width:1040px;margin:40px auto;padding:0 24px}}header{{background:#0e1722;color:white;padding:28px;border-radius:14px;display:flex;justify-content:space-between;gap:24px}}.brand{{color:#2797ff;font-weight:900;font-style:italic;font-size:19px}}h1{{font-size:25px;margin:16px 0 5px;overflow-wrap:anywhere}}header p{{color:#aab6c4;margin:0}}.score{{min-width:150px;text-align:center;border:1px solid #334254;border-radius:10px;padding:14px}}.score strong{{display:block;color:{color};font-size:32px}}.panel{{background:white;border:1px solid #dfe4ea;border-radius:12px;padding:22px;margin-top:18px}}h2{{margin:0 0 16px;font-size:17px}}.finding{{display:grid;grid-template-columns:7px 1fr auto;gap:14px;padding:14px 0;border-top:1px solid #edf0f3}}.finding:first-of-type{{border-top:0}}.finding i{{border-radius:5px}}.finding h3{{margin:0 0 5px;font-size:14px}}.finding p{{margin:0;color:#5f6b77;line-height:1.5}}table{{border-collapse:collapse;width:100%}}th,td{{padding:10px;text-align:left;border-bottom:1px solid #edf0f3;vertical-align:top;overflow-wrap:anywhere}}th{{width:210px;color:#66727e;font-weight:600}}pre{{white-space:pre-wrap;overflow-wrap:anywhere;background:#f6f8fa;padding:12px;border-radius:7px;font:12px ui-monospace,monospace}}footer{{color:#77828e;text-align:center;padding:24px}}@media(max-width:650px){{header{{display:block}}.score{{margin-top:18px}}th{{width:120px}}}}
</style></head><body><main>
<header><div><div class="brand">THZCodeSpair</div><h1>{html.escape(result.name)}</h1><p>Static inspection · The file was not executed or uploaded</p></div><div class="score"><span>RISK SCORE</span><strong>{result.score}/100</strong>{html.escape(result.verdict)}</div></header>
<div class="panel"><h2>Findings</h2>{findings}</div>
<div class="panel"><h2>Technical details</h2><table>{rows}</table></div>
<div class="panel"><h2>Indicators</h2>{indicators}</div>
<footer>Generated by THZCodeSpair File Inspector · {datetime.now().astimezone().strftime('%Y-%m-%d %H:%M:%S %Z')}</footer>
</main></body></html>"""
    path.write_text(document, encoding="utf-8")
    return path
